# Generated by Django 5.0.14 on 2025-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_req',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
