# Generated by Django 5.0.14 on 2025-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_dir',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
