# Generated by Django 5.0.14 on 2025-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivos', '0003_user_dir_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_dir',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
