# Generated by Django 5.2.1 on 2025-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_requisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
