# Generated by Django 5.2.1 on 2025-05-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_requisicion_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicion',
            options={},
        ),
    ]
