# Generated by Django 5.2.1 on 2025-05-15 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_requisicion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('archivo', models.FileField(upload_to='ordenes_compra/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_esperada', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('E', 'Enviada'), ('R', 'Recibida'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.user_com')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='compras.requisicion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
