# Generated by Django 5.0.14 on 2025-05-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordencompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotiz_p',
            fields=[
                ('fac_mun', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'reqisiciones',
                'db_table': 'cotiz_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('co_prov', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prov_des', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'prov',
                'managed': False,
            },
        ),
    ]
