# Generated by Django 5.0.14 on 2025-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_cotiz_p_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotiz_p',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='archivo_aprobacion',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_aprobacion/'),
        ),
    ]
