# Generated by Django 5.0.14 on 2025-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_delete_cotiz_p_ordencompra_archivo_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='archivo_cuadro_comparativo',
            field=models.FileField(blank=True, null=True, upload_to='cuadros_comparativos/'),
        ),
    ]
