# Generated by Django 5.0.14 on 2025-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_ordencompra_archivo_cuadro_comparativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('N', 'Negada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('N', 'Negada')], default='P', max_length=1),
        ),
    ]
