# Generated by Django 5.0.14 on 2025-05-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_ordencompra_estado_alter_requisicion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='creador_req',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
