# Generated by Django 5.0.14 on 2025-05-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_requisicion_creador_req'),
        ('directivos', '0002_user_dir_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='directivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_recibidas', to='directivos.user_dir'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='importancia',
            field=models.CharField(choices=[('N', 'Normal'), ('U', 'Urgente')], default='N', max_length=1),
        ),
    ]
