# Generated by Django 5.0.14 on 2025-06-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_requisicion_directivo_requisicion_importancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_com',
            name='tipo_compras',
            field=models.CharField(choices=[('servicios', 'Servicios'), ('ferreteria', 'Ferretería'), ('repuestos', 'Repuestos'), ('suministros', 'Suministros'), ('vacunas', 'Vacunas')], default='servicios', max_length=20),
        ),
    ]
