# Generated by Django 5.0.14 on 2025-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_user_com_tipo_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_com',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
