# Generated by Django 5.0.14 on 2025-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_user_com_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_com',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
